### ISSUE TITLE
Error in testing code - refresh.py

### ISSUE THREAD

**Issue by khelm** [incf-nidash/nidm#410] opened 2017-05-26 15:50 UTC
I ran refresh.py and got:
```
karl@karl-Satellite-C655D:~/Work/INCF/nidm/nidm$ python scripts/refresh.py
Traceback (most recent call last):
  File "scripts/refresh.py", line 17, in <module>
    import recompute_all_ex
  File "/home/karl/Work/INCF/nidm/nidm/scripts/../nidm/nidm-results/scripts/recompute_all_ex.py", line 9, in <module>
    import create_term_examples
  File "/home/karl/Work/INCF/nidm/nidm/scripts/../nidm/nidm-results/scripts/create_term_examples.py", line 10, in <module>
    from create_example_from_templates import ExampleFromTemplate
  File "/home/karl/Work/INCF/nidm/nidm/scripts/../nidm/nidm-results/scripts/create_example_from_templates.py", line 78
    except KeyError, k:
                   ^
SyntaxError: invalid syntax
```

I believe this is a current error since I just merged my master with the upstream master.

**Comment by cmaumet** [comment] 2017-06-01 10:42
Hi @khelm! Could you point me to which branch you are running this on? That would help me reproduce the error locally to track this down. Thanks!

**Comment by khelm** [comment] 2017-06-01 14:57
the branch is khelm:reconcile_with_lucidchart_ver7

**Comment by cmaumet** [comment] 2017-06-01 15:23
Have you recently updated to python 3? I can reproduce the error with py3 but the command runs fine with python 2. Ideally `refresh.py` should handle both python versions...

**Comment by khelm** [comment] 2017-06-01 15:30
I have two instances of python of that computer and thought that it was currently pointing to 2.7, but maybe not, I'll check - thanks!

**Comment by khelm** [comment] 2017-06-01 20:50
After pointing to python 2.7 I now get the following error:

(py27) karl@karl-Satellite-C655D:~/Work/INCF/nidm/nidm$ python scripts/refresh.py
Traceback (most recent call last):
  File "scripts/refresh.py", line 17, in <module>
    import recompute_all_ex
  File "/home/karl/Work/INCF/nidm/nidm/scripts/../nidm/nidm-results/scripts/recompute_all_ex.py", line 9, in <module>
    import create_term_examples
  File "/home/karl/Work/INCF/nidm/nidm/scripts/../nidm/nidm-results/scripts/create_term_examples.py", line 10, in <module>
    from create_example_from_templates import ExampleFromTemplate
  File "/home/karl/Work/INCF/nidm/nidm/scripts/../nidm/nidm-results/scripts/create_example_from_templates.py", line 22, in <module>
    from nidmresults.owl.owl_reader import OwlReader
ImportError: No module named nidmresults.owl.owl_reader

**Comment by cmaumet** [comment] 2017-06-05 16:13
@khelm: This looks like the `nidmresults` module is missing. Can you check if all the packages from `requirements.txt` are installed (within your py 2.7 environment).

**Comment by khelm** [comment] 2017-06-05 16:21
@cmaumet : Thanks, I see what happened.  I lost some of my packages when I moved to setting up separate 2.7 and 3.6 anaconda python environments.  I'll reinstall and rerun.

**Comment by cmaumet** [comment] 2017-06-06 09:15
Excellent! I can see that you have updated your PR at https://github.com/incf-nidash/nidm/pull/409 so hopefully the problem is solved now?

**Comment by khelm** [comment] 2017-06-06 14:31
@cmaumet : I fixed a formatting issue that was giving a different type of warning and reran the tests.  Now everything passes and is ready to merge.  Thanks for your help!

**Comment by cmaumet** [comment] 2017-06-06 14:44
That's great! Let's close this issue.

**Closed by cmaumet** 2017-06-06 14:44 UTC
